# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doggl < Formula
  desc "Simple toggl client for work time tracking."
  homepage ""
  version "1.6.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tubenhirn/doggl/releases/download/v1.6.4/doggl_1.6.4_Darwin_arm64.tar.gz"
      sha256 "204c436d0256930d45994b987dda8daaf3a10691468414368a5cb5687e6032f6"

      def install
        bin.install "darwin_arm64/doggl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tubenhirn/doggl/releases/download/v1.6.4/doggl_1.6.4_Darwin_x86_64.tar.gz"
      sha256 "e85e2524ebbe9300eb58258300586ba706af2d7e84edca05cec2519ad8fd9762"

      def install
        bin.install "darwin_amd64_v1/doggl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tubenhirn/doggl/releases/download/v1.6.4/doggl_1.6.4_Linux_x86_64.tar.gz"
      sha256 "a0f44aefb288213216b1bcabe747883023d44997c950ff22414a5d7372ee01ef"

      def install
        bin.install "linux_amd64_v1/doggl"
      end
    end
  end
end
