# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rasic < Formula
  desc "Wrapper for trivy scanner with incident creation."
  homepage ""
  version "1.17.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tubenhirn/rasic/releases/download/v1.17.3/rasic_1.17.3_Darwin_arm64.tar.gz"
      sha256 "7d6dd51eada7ffd6ed7eb1bd4b5462005a634257b0de30487a4fa683f1fc43bd"

      def install
        bin.install "darwin_arm64/plugins/reporter/reporter_gitlab"
        bin.install "darwin_arm64/plugins/source/source_gitlab"
        bin.install "darwin_arm64/rasic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tubenhirn/rasic/releases/download/v1.17.3/rasic_1.17.3_Darwin_x86_64.tar.gz"
      sha256 "15f37dcf86daea29a8f69eb5968fcb4c76814511e48c30d676042cfaf8f853a0"

      def install
        bin.install "darwin_amd64_v1/plugins/reporter/reporter_gitlab"
        bin.install "darwin_amd64_v1/plugins/source/source_gitlab"
        bin.install "darwin_amd64_v1/rasic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tubenhirn/rasic/releases/download/v1.17.3/rasic_1.17.3_Linux_x86_64.tar.gz"
      sha256 "2e285746d6c2aab4fcf889330b4af5c8950bd504ff4d471fbc737f61d0cdd79e"

      def install
        bin.install "linux_amd64_v1/plugins/reporter/reporter_gitlab"
        bin.install "linux_amd64_v1/plugins/source/source_gitlab"
        bin.install "linux_amd64_v1/rasic"
      end
    end
  end
end
